version: "3"
services:
  node_alice:
    build:
      context: .
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    image: alexcj96/rococo-v1:f3e2cbf4
    volumes:
      - "polkadot-data-alice:/data"
    command: polkadot --chain=/polkadot/rococo_local.json --alice -d /data --validator --node-key 0000000000000000000000000000000000000000000000000000000000000001
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    build:
      context: .
    ports:
      - "30344:30344"
      - "9935:9935"
      - "9945:9945"
    image: alexcj96/rococo-v1:f3e2cbf4
    volumes:
      - "polkadot-data-bob:/data"
    links:
      - "node_alice:alice"
    command: polkadot --chain=/polkadot/rococo_local.json --bob -d /data --validator --port 30344 --rpc-port 9935 --ws-port 9945 --bootnodes '/ip4/172.28.1.1/tcp/30333/p2p/12D3KooWGJN46S9vxi46QAfk211jm3ugzTNUg3Tn7Zy1PieCqpYh'
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  node_collator:
    build:
      context: .
    depends_on:
      - node_alice
      - node_bob
    ports:
      - "30345:30345"
      - "9936:9936"
      - "9946:9946"
    image: alexcj96/parallel:latest
    volumes:
      - "polkadot-data-collator:/data"
    links:
      - "node_alice:alice"
    command: parallel --chain=/parallel/rococo_local.json --alice -d /data --collator --port 30345 --rpc-port 9936 --ws-port 9946 --parachain-id 200 --bootnodes '/ip4/172.28.1.1/tcp/30333/p2p/12D3KooWGJN46S9vxi46QAfk211jm3ugzTNUg3Tn7Zy1PieCqpYh'
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

volumes:
  polkadot-data-alice:
  polkadot-data-bob:
  polkadot-data-collator:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
