name: Docker Image

on:
  push:
    branches: [master]
    tags:
      - "v*"

jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: haya14busa/action-cond@v1
        id: docker_tag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${GITHUB_REF/refs\/tags\//}
          if_false: "latest"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.release
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ steps.docker_tag.outputs.value }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
